version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
  local:
    image: mariadb:10.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=yii2basic
    ports:
      - '3307:3306'
    expose:
      - '3307'
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_unicode_ci', '--skip-name-resolve']
  local_redis:
    image: redis:latest
    ports:
      - '6380:6379'
    expose:
      - '6380'
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master